#!/bin/bash

# The pre_start_cartridge and pre_stop_cartridge hooks are *SOURCED*
# immediately before (re)starting or stopping the specified cartridge.
# They are able to make any desired environment variable changes as
# well as other adjustments to the application environment.

# The post_start_cartridge and post_stop_cartridge hooks are executed
# immediately after (re)starting or stopping the specified cartridge.

# Exercise caution when adding commands to these hooks.  They can
# prevent your application from stopping cleanly or starting at all.
# Application start and stop is subject to different timeouts
# throughout the system.

# Sidekiq

set -e

echo "Stopping the default server..."
gear stop

echo "Starting Redis..."
pushd ${OPENSHIFT_REDIS_DIR} > /dev/null
bin/control start

pushd ${OPENSHIFT_REPO_DIR} > /dev/null
echo "Starting sidekiq..."
bundle exec "sidekiq -d -r ./initialize.rb -P '${OPENSHIFT_DATA_DIR}sidekiq.pid' -L '${OPENSHIFT_DATA_DIR}sidekiq.log'"

pushd ${OPENSHIFT_REPO_DIR} > /dev/null
nohup bundle exec "rackup config.ru -s puma -E production" &> ${OPENSHIFT_DATA_DIR}puma.log &
echo $! > "${OPENSHIFT_DATA_DIR}puma.pid"

exit 0
