<% if File.exists?(File.expand_path('./.env', __FILE__)) %>
development:
  adapter: postgresql
  database: supermarket_development
  host: localhost
  pool: 30
<% else %>
development:
  adapter: postgresql
  database: <%=ENV['OPENSHIFT_APP_NAME']%>
  username: <%=ENV['OPENSHIFT_POSTGRESQL_DB_USERNAME']%>
  password: <%=ENV['OPENSHIFT_POSTGRESQL_DB_PASSWORD']%>
  host:     <%=ENV['OPENSHIFT_POSTGRESQL_DB_HOST']%>
  port:     <%=ENV['OPENSHIFT_POSTGRESQL_DB_PORT']%>
  pool: 30
  min_messages: ERROR
  reconnect: false
<% end %>

test:
  adapter: postgresql
  database: supermarket_test
  host: localhost

production:
  username: <%= ENV['OPENSHIFT_POSTGRESQL_DB_USERNAME'] %>
  password: <%= ENV['OPENSHIFT_POSTGRESQL_DB_PASSWORD'] %>
  host: <%= ENV['OPENSHIFT_POSTGRESQL_DB_HOST'] %>
  adapter: postgresql
  database: manageiq
