development:
  adapter: postgresql
  database: supermarket_development
  host: localhost
  pool: 30

test:
  adapter: postgresql
  database: supermarket_test
  host: localhost

production:
  username: <%= ENV['OPENSHIFT_POSTGRESQL_DB_USERNAME'] %>
  password: <%= ENV['OPENSHIFT_POSTGRESQL_DB_PASSWORD'] %>
  host: <%= ENV['OPENSHIFT_POSTGRESQL_DB_HOST'] %>
  adapter: postgresql
  database: manageiq
